@echo off
chcp 65001
setlocal
set name=
echo 1 "당신이 모르는 것"
echo 2 "천성의 약함"
echo 3 "Believe in you"
echo 4 "생명에게 미움받고 있어"
echo 5 "여자아이가 되고 싶어"
echo 6 "말 없는 흑백합"
echo 7 "ADAMAS"
echo 8 "거센 외로움이 덮쳐와"
echo 9 "윤회전생"
echo 10 "닌자의 권유"
echo 11 "새크리파이스"
echo 12 "테오"
echo 13 "히바나"
echo 14 "타상연화"
echo 15 "친애하는 도플갱어에게"
echo 16 "테러"
echo 17 "KING"
echo 18 "ECHO"
echo 19 "RAIN"
echo 20 "Pretender"
echo 21 "샤를"
echo 22 "꽃내림"
echo 23 "꽃에 망령"
echo 24 "병명은 사랑이었다"
echo 25 "수꽃의 눈물"
echo 26 "진흙속에 피다"
echo 27 "잊지못할 언어"
echo 28 "COSMOS"
set /p name=번호를 입력하세요:
npx electron test "%name%"
