@echo off
setlocal
set name=
echo 1 "당신이 모르는 것"
echo 2 "천성의 약함"
echo 3 "Believe in you"
echo 4 "생명에게 미움받고 있어"
echo 5 "여자아이가 되고 싶어"
echo 6 "말 없는 흑백합"
echo 7 "ADAMAS"
echo 8 "거센 외로움이 덮쳐와"
echo 9 "윤회전생"
echo 10 "닌자의 권유"
echo 11 "새크리파이스"
echo 12 "테오"
echo 13 "히바나"
echo 14 "타상연화"
echo 15 "친애하는 도플갱어에게"
echo 16 "테러"
echo 17 "KING"
echo 18 "ECHO"
echo 19 "RAIN"
echo 20 "Pretender"
echo 21 "샤를"
echo 22 "꽃내림"
echo 23 "꽃에 망령"
echo 24 "병명은 사랑이었다"
echo 25 "수꽃의 눈물"
echo 26 "진흙속에 피다"
echo 27 "잊지못할 언어"
echo 28 "COSMOS"
echo 29 "태어난 의미따위 없었다"
echo 30 "그것이 당신의 행복이라 할지라도"
echo 31 "Ghost Rule"
echo 32 "사랑이 시작되는 방정식"
echo 33 "소녀해부"
echo 34 "자상무색"
echo 35 "Grand Escape"
echo 36 "전전전생"
echo 37 "그 목소리가 사라지지 않아"
echo 38 "연애재판"
echo 39 "내일의 밤하늘 초계반"
set /p name=번호를 입력하세요:
npx electron test "%name%"